[theme]
light = "monokai_pro_light"
dark = "monokai_pro"

[editor]
# try and make this more friendly for dvorak
jump-label-alphabet = "hutenodasicrpymwkxlfgvbjqz"
line-number = "relative"

[editor.lsp]
display-inlay-hints = true
# display-messages = true
[editor.inline-diagnostics]
# cursor-line = "warning"
# end-of-line-diagnostics = "error"
# other-lines = "error"

[editor.file-picker]
# enable viewing hidden files:
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"A-tab" = "completion"

[keys.normal]
# old habits die hard
"0" = "goto_line_start"
# This does not seem to work for some reason:
"Cmd-C-S-h" = "expand_selection"
X = "select_line_above"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.normal.backspace]
w = ":write-all"
r = ":reload-all"
R = [":reload-all", ":config-reload"]
"," = ":config-open"
