[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
feature_words = false                # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

[[language]]
name = "markdown"
language-servers = [ "scls", "oxfmt", "marksman" ]

soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""

[[language]]
name = "rust"
auto-format = true
language-servers = [ "scls", "rust-analyzer"  ]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "oxlint",
  "oxfmt"
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "oxlint",
  "oxfmt"
]
auto-format = true

[[language]]
name = "json"
language-servers = [
  "vscode-json-language-server",
  "oxfmt"
]
auto-format = true

[[language]]
name = "json5"
language-servers = [
  "vscode-json-language-server",
  "oxfmt"
]
auto-format = true

[[language]]
name = "jsonc"
language-servers = [
  "vscode-json-language-server",
  "oxfmt"
]
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "oxlint",
  "oxfmt"
]
auto-format = true

[language-server.oxlint]
command = "oxlint"
args = ["--lsp"]

[language-server.oxfmt]
command = "oxfmt"
args = ["--lsp"]

