[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[typst]
symbol = "t "

[gcloud]
disabled = true

[aws]
disabled = true

[time]
disabled = true
utc_time_offset = "0"
format = "[$time UTC]($style) "
style = ""

[direnv]
disabled = false

[git_branch]
disabled = true

[git_status]
disabled = true
