# zsh init file -*- mode: shell-script; -*-
# Chris Farber, Nov 2009

#general options
setopt extendedglob
unsetopt CASE_GLOB
setopt autopushd
setopt dvorak
setopt nobeep
fpath=(~/.zsh/functions $fpath)
fpath=(/usr/local/share/zsh-completions $fpath)

if [[ -n `whence colorls` ]]; then
  alias ls="colorls -FG" # this is for OpenBSD
elif [[ $(uname) == "Darwin" ]]; then
  alias ls="ls -FG"
else
  alias ls="ls -F --color"
fi

#custom prompt
source $HOME/.cfgit.zsh
function check_last_exit_code() {
  local LAST_EXIT_CODE=$?
  if [[ $LAST_EXIT_CODE -ne 0 ]]; then
    local EXIT_CODE_PROMPT=""
    EXIT_CODE_PROMPT+="%F{red}-$LAST_EXIT_CODE-%f "
    echo "$EXIT_CODE_PROMPT"
  fi
}
export PROMPT='%F{green}%n%f@%F{yellow}%m%f:%F{blue}%1~%f $(check_last_exit_code)$(cfgit_prompt)%# '
export PROMPT='%F{magenta}%m%f: %F{cyan}%1~%f $(check_last_exit_code)$(cfgit_prompt)%# '
export RPROMPT='%@'

#key bindings
#bindkey -v
bindkey \^R history-incremental-search-backward
bindkey \^S history-incremental-search-forward
stty stop undef #disable ^s so the bindkey works


#history
export SAVEHIST=1000000
export HISTSIZE=1000000
export HISTFILE=~/.zhistory
setopt sharehistory
setopt incappendhistory
setopt extendedhistory

# Fix Emacs's TRAMP with zsh, by disabling my fancy prompt:
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '' '' 'r:|[._-]=* r:|=*'
zstyle :compinstall filename '/Users/chrisfarber/.zshrc'

autoload -Uz compinit
compinit -u
# End of lines added by compinstall

for file in ~/.zshrc.d/*; do
  source $file
done
